######################################################################
# Automatically generated by qmake (2.01a) Sat May 25 01:59:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../lib
INCLUDEPATH += . ../include

MOC_DIR += /tmp
OBJECTS_DIR += /tmp

# Input
HEADERS += mainwindow.h ../include/heatmapper.h ../include/gradientpalette.h
SOURCES += main.cpp mainwindow.cpp ../lib/heatmapper.cpp ../lib/gradientpalette.cpp
