######################################################################
# Automatically generated by qmake (2.01a) Sat May 25 02:01:48 2013
######################################################################

TEMPLATE = subdirs
SUBDIRS = lib
SUBDIRS += test
