######################################################################
# Automatically generated by qmake (2.01a) Sat May 25 01:58:33 2013
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = lib
TARGET = qheatmap
DEPENDPATH += .
INCLUDEPATH += . ../include/

unix: {
   MOC_DIR += /tmp
   OBJECTS_DIR += /tmp
}

DEFINES += QHEATMAP_DLL_LIBRARY

# Input
SOURCES += heatmapper.cpp ./gradientpalette.cpp
