######################################################################
# Automatically generated by qmake (2.01a) Sat May 25 01:58:33 2013
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../include/

MOC_DIR += /tmp
OBJECTS_DIR += /tmp

# Input
SOURCES += heatmapper.cpp
